<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="HO-SVS-MAMALLAN-LAP" name="org.testngannota.RerunTestCases" tests="7" failures="1" timestamp="19 Jun 2022 06:46:01 GMT" time="76.946" errors="0">
  <testcase name="tc3" time="44.193" classname="org.testngannota.RerunTestCases"/>
  <testcase name="tc4" time="0.042" classname="org.testngannota.RerunTestCases">
    <skipped/>
  </testcase> <!-- tc4 -->
  <testcase name="tc2" time="0.025" classname="org.testngannota.RerunTestCases"/>
  <testcase name="tc4" time="0.012" classname="org.testngannota.RerunTestCases">
    <skipped/>
  </testcase> <!-- tc4 -->
  <testcase name="tc1" time="32.652" classname="org.testngannota.RerunTestCases"/>
  <testcase name="tc4" time="0.011" classname="org.testngannota.RerunTestCases">
    <failure type="java.lang.AssertionError" message="Please check the tc4 title expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Please check the tc4 title expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testngannota.RerunTestCases.tc4(RerunTestCases.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- tc4 -->
  <testcase name="tc4" time="0.011" classname="org.testngannota.RerunTestCases">
    <skipped/>
  </testcase> <!-- tc4 -->
</testsuite> <!-- org.testngannota.RerunTestCases -->
